name: PhysioKit CI

on: [push]

env:
  PYTHON_VERSION: '3.11'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Run Tests 🔧
        run: |
          uv sync
          uv run ruff check
          uv run pytest tests/
